AllCops:
  Exclude:
    - 'examples/*'
    - 'tasks/**/*.rake'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - Rakefile
    - gir_ffi.gemspec
  DisplayCopNames: true

# Dot at end of line makes it clearer that the line is not done
Layout/DotPosition:
  EnforcedStyle: trailing

# Multi-line assignment should be simply indented. Aligning them makes it even
# harder to keep a sane line length.
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

# Multi-line method calls should be simply indented. Aligning them makes it
# even harder to keep a sane line length.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# This cop gives bad advice
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Test describe blocks can be any size
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92

# Lib modules can be any length
Metrics/ModuleLength:
  Exclude:
    - 'lib/ffi-gobject_introspection/lib.rb'

# Gtk+ has a lot of accessor method starting with get_ or set_
Naming/AccessorMethodName:
  Enabled: false

# GirFFI uses a ffi-something naming scheme.
Naming/FileName:
  Enabled: false

# TODO: See about has_ and have_
Naming/PredicateName:
  NamePrefixBlacklist:
    - is_

# This cop is broken
Naming/VariableNumber:
  Enabled: false

# In tests, we want to do this to be more clear
Performance/FixedSize:
  Exclude:
    - 'test/**/*.rb'

# Conform to old RuboCop behavior for now
Style/Alias:
  EnforcedStyle: prefer_alias_method

# Allow and/or for control flow only
Style/AndOr:
  EnforcedStyle: conditionals

# Comment all the files!
Style/FrozenStringLiteralComment:
  EnforcedStyle: always

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# Don't use if or unless as modifier if the line gets too long
Style/IfUnlessModifier:
  MaxLineLength: 60

# Sometimes an if statement just looks better than next with a guard clause
Style/Next:
  Enabled: false

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# Allow meaningful names for single-line reduce etc.
Style/SingleLineBlockParams:
  Enabled: false

# I like to have symbols always look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets

# Accessors are only trivial if they match the ivar name.
# Also, allow accessors with ? in the name.
Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true

inherit_from: .rubocop_todo.yml
