---
language: ruby

dist: xenial

before_install:
  - sudo apt-get update
  # Provides libgirepository-1.0.so.1
  - sudo apt-get install libgirepository-1.0-1
  # Provides source code for test libraries and tools to generate introspection data
  - sudo apt-get install gobject-introspection
  # The regress.c test library needs cairo headers
  - sudo apt-get install libcairo2-dev
  # Provides gir files for various libraries, needed for generating gir files
  # for test libraries
  - sudo apt-get install libgirepository1.0-dev
  # The following packages provide typelibs for various libraries
  - sudo apt-get install gir1.2-gtop-2.0
  - sudo apt-get install gir1.2-gtk-3.0
  - sudo apt-get install gir1.2-pango-1.0
  - sudo apt-get install gir1.2-secret-1
  - sudo apt-get install gir1.2-gstreamer-1.0
  - sudo apt-get install gir1.2-gtksource-3.0

cache:
  bundler: true

script: bundle exec rake

# - Run full test suite on MRI
# - Do not run cucumber scenarios on JRuby
# - Run rubocop on MRI 2.7.1
jobs:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: ruby-head
    - rvm: jruby-9.2
      script: bundle exec rake test:all
    - rvm: jruby-head
      script: bundle exec rake test:all
    - rvm: 2.7.1
      name: "RuboCop"
      before_install: []
      script: bundle exec rubocop
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

branches:
  only:
    - master
